"""Write CORRECTIONS.md for one station: how every water scan was corrected, scan by scan.

    python make_corrections_doc.py Data_NatureSpec/2026_Aug_17/by_location/LOC5_*/FLENS8_FOV08

Every number is recomputed from the scans with the same calls and flags that built this
station's FINAL_Rrs.csv (glint method and exclusions are read back from its REPORT.txt),
or parsed from that run's own outputs. Nothing is typed by hand. Hand-written judgement
(why a scan was dropped, why an angle was assumed) goes in an optional STATION_NOTES.md
next to the scans, which is included verbatim and labelled as such.

Run after analyse_location.py and analyse_water_scans.py. Regenerate after any re-run;
do not edit the output.
"""

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np

from analyse_location import match_by_angle
from fieldrrs.rrs import rho_at_angle, rrs_three_scan, view_zenith_from_tilt
from make_all_spectra_figs import _excluded_of, _glint_of
from organize_by_location import survey
from process_field_day import band

PANEL_R = 0.99
BANDS = (443, 555, 665, 865)


def _at(wl, y, lam):
    return float(y[int(np.argmin(np.abs(wl - lam)))])


def _report_line(text, pattern, default="n/a"):
    m = re.search(pattern, text)
    return m.group(1).strip() if m else default


def _verdicts(loc):
    """Step-5 verdict per scan from analysis/water_scans/REPORT.txt."""
    p = os.path.join(loc, "analysis", "water_scans", "REPORT.txt")
    if not os.path.exists(p):
        return {}
    out = {}
    for line in open(p).read().split("VERDICT PER SCAN", 1)[-1].splitlines()[2:]:
        f = line.split()
        if len(f) >= 9 and f[0].isdigit():
            out[f[0]] = " ".join(f[8:])
        elif out:
            break
    return out


def _final(path):
    d = np.genfromtxt(path, delimiter=",", skip_header=2)
    return d[:, 0], d[:, 1]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("location", help="by_location/LOC*/FOREOPTIC_FOVxx")
    a = ap.parse_args()
    loc = a.location.rstrip("/")
    rpt_path = os.path.join(loc, "analysis", "REPORT.txt")
    if not os.path.exists(rpt_path):
        raise SystemExit("%s missing: run analyse_location.py first" % rpt_path)
    if not os.path.exists(os.path.join(loc, "analysis", "FINAL_Rrs.csv")):
        raise SystemExit("%s has no FINAL_Rrs.csv: not an R_rs station (e.g. a "
                         "reflectance-only land target), nothing to document" % loc)
    rpt = open(rpt_path).read()
    glint = _glint_of(loc)
    excl = _excluded_of(loc)
    verdict = _verdicts(loc)

    scans = survey(loc)
    wl = np.array(scans[0]["spec"].wavelength)
    sky = [s for s in scans if s["role"] == "sky"]
    water = sorted([s for s in scans if s["role"] == "water"], key=lambda s: s["n"])
    land = [s for s in scans if s["role"] == "land"]
    pairs = match_by_angle(water, sky)

    rows = []
    for w, sk, dm, note in pairs:
        tilt = w["spec"].tilt_y_deg
        th = view_zenith_from_tilt(tilt)
        rho = rho_at_angle(th)
        lt, ls, lp = (w["spec"].columns["rad_target"], sk["spec"].columns["rad_target"],
                      w["spec"].columns["rad_ref"])
        raw = rrs_three_scan(wl, lt, ls, lp, PANEL_R, rho, "none")
        cor = rrs_three_scan(wl, lt, ls, lp, PANEL_R, rho, glint)
        surf = rho * np.array(ls)
        rows.append({
            "n": w["n"], "sky": sk["n"], "tilt": tilt, "theta": th, "dtheta": dm,
            "rho": rho, "ref": band(w["spec"], "rad_ref", 450, 650),
            "surf443": 100 * _at(wl, surf, 443) / _at(wl, np.array(lt), 443),
            "eps": cor.offset,
            "raw": {b: _at(wl, np.array(raw.rrs), b) for b in BANDS},
            "cor": {b: _at(wl, np.array(cor.rrs), b) for b in BANDS},
            "excluded": w["n"] in excl,
            "verdict": verdict.get(w["n"], "n/a"),
        })

    name = os.path.basename(os.path.dirname(loc)) + " / " + os.path.basename(loc)
    L = []
    P = L.append
    P("# Corrections, scan by scan: %s" % name)
    P("")
    P("Generated by `make_corrections_doc.py` from this station's scans and its own run "
      "outputs. Do not edit; re-run the generator after any re-processing.")
    P("")
    P("## Run")
    P("")
    P("| item | value |")
    P("|---|---|")
    P("| scans | %d (%d water, %d sky, %d land) |" % (len(scans), len(water), len(sky), len(land)))
    P("| time / sun | %s |" % _report_line(rpt, r"\d+ scans\s+(\S+ UTC\s+sun [^\n]+)"))
    P("| position spread | %s |" % _report_line(rpt, r"all scans within (\d+ m)"))
    P("| panel references | %s |" % _report_line(rpt, r"(\d+) distinct panel references"))
    P("| glint correction | `%s` |" % glint)
    P("| excluded water scans | %s |" % (", ".join(sorted(excl)) or "none"))
    P("| E_d check | %s |" % _report_line(rpt, r"VERDICT: ([^\n]+)"))
    P("| median transmittance 450-650 nm | %s |" % _report_line(rpt, r"median T over 450-650 nm\s+(\S+)"))
    P("| sky-water angle mismatch | %s |" % _report_line(rpt, r"mismatch (mean [^\n]+)"))
    P("")
    P("## The correction chain")
    P("")
    P("For each water scan, with its angle-matched sky scan and the panel reference "
      "stored with it:")
    P("")
    P("1. E_d = π L_panel / R_panel, R_panel = %.2f." % PANEL_R)
    P("2. ρ(θ_v) = 0.028 · R_F(θ_v) / R_F(40°) (Mobley 1999, scaled by the Fresnel ratio), "
      "θ_v = |tilt Y|.")
    P("3. R_rs = (L_t − ρ L_sky) / E_d.")
    if glint == "nir_similarity":
        P("4. Glint: a spectrally flat ε is subtracted so that R_rs(780)/R_rs(870) "
          "matches the Ruddick et al. (2006) similarity ratio for turbid water.")
    elif glint == "nir_zero":
        P("4. Glint: the 750-800 nm mean is subtracted (R_rs assumed 0 there).")
    else:
        P("4. Glint: none applied.")
    P("5. FINAL: iterative amplitude-normalised mean of the kept scans "
      "(THEORY_SCALED_MEAN.md).")
    P("")
    P("## Per scan")
    P("")
    P("ρL_sky/L_t is the share of the measured radiance at 443 nm removed as reflected "
      "sky. ε is the glint offset subtracted in step 4 (sr⁻¹). R_rs in sr⁻¹ before and "
      "after step 4.")
    P("")
    P("| water | sky | tilt ° | Δθ ° | ρ | ρL_sky/L_t 443 | ε | R_rs555 before | "
      "R_rs555 after | R_rs865 after | step-5 verdict | in FINAL |")
    P("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        P("| %s | %s | %.1f | %.1f | %.4f | %.0f %% | %+.5f | %.5f | %.5f | %.5f | %s | %s |"
          % (r["n"], r["sky"], r["tilt"], r["dtheta"], r["rho"], r["surf443"], r["eps"],
             r["raw"][555], r["cor"][555], r["cor"][865], r["verdict"],
             "**no**" if r["excluded"] else "yes"))
    kept = [r for r in rows if not r["excluded"]]
    if kept:
        eps = np.array([r["eps"] for r in kept])
        P("")
        P("Kept scans: ε = %+.5f ± %.5f sr⁻¹ (mean ± sd). Reflected sky is %.0f-%.0f %% of the measured "
          "radiance at 443 nm." % (eps.mean(), eps.std(),
                               min(r["surf443"] for r in kept), max(r["surf443"] for r in kept)))
    if land:
        P("")
        P("Land-classified scans (reflectance only, never in R_rs): %s."
          % ", ".join(sorted(s["n"] for s in land)))
    P("")
    P("## Result")
    P("")
    shape = _report_line(rpt, r"SHAPE\s+([\d.]+ %)")
    amp = _report_line(rpt, r"AMPLITUDE\s+([\d.]+ %)")
    w1, f1 = _final(os.path.join(loc, "analysis", "FINAL_Rrs.csv"))
    P("Shape (450-700 nm) %s, amplitude %s." % (shape, amp))
    P("")
    hdr = "| product | " + " | ".join("R_rs(%d)" % b for b in BANDS) + " |"
    P(hdr)
    P("|---" * (len(BANDS) + 1) + "|")
    P("| FINAL (%s) | " % glint + " | ".join("%.5f" % _at(w1, f1, b) for b in BANDS) + " |")
    alt = os.path.join(loc, "analysis_glint_none", "FINAL_Rrs.csv")
    if os.path.exists(alt):
        w0, f0 = _final(alt)
        rpt0 = open(os.path.join(loc, "analysis_glint_none", "REPORT.txt")).read()
        P("| without glint correction (analysis_glint_none/) | "
          + " | ".join("%.5f" % _at(w0, f0, b) for b in BANDS) + " |")
        P("")
        P("Without the glint correction: shape %s, amplitude %s."
          % (_report_line(rpt0, r"SHAPE\s+([\d.]+ %)"),
             _report_line(rpt0, r"AMPLITUDE\s+([\d.]+ %)")))
    notes = os.path.join(loc, "STATION_NOTES.md")
    if os.path.exists(notes):
        P("")
        P("## Station notes (hand-written, from STATION_NOTES.md)")
        P("")
        P(open(notes).read().strip())
    P("")
    out = os.path.join(loc, "CORRECTIONS.md")
    open(out, "w").write("\n".join(L))
    print("wrote %s (%d water scans)" % (out, len(rows)))


if __name__ == "__main__":
    main()
